In [13]:
import os
import pandas as pd
import numpy as np

pathname = ""
#has 46 csv files with the top 50 songs with audio feature tags
years = ["2017","2018","2019"]
regions = ["us","gb", "ar", "at", "au", "be", "bg",
               "bo", "br", "ca", "ch", "cl", "co", "cy", "cz", "de",
               "dk", "es", "fi", "fr", "hk",
               "hn", "hu", "id", "ie", "is", "it", "jp", "lu", "lv",
               "mx", "my", "ni", "no", "pe",
               "ph", "pl", "pt", "py", "se", "sg", "sk", "sv", "tr", "tw", "uy"]
len(regions)

46

In [10]:
filepath = "/Users/lalitha/Documents/worldhappinessmusic/countrycodes.csv"
df_codes = pd.read_csv(filepath)
countries_dict = {}
for i, j in df_codes.iterrows():
    country_code = df_codes["Country Code"][i].lower()
    if country_code in regions:
        countries_dict[country_code] = df_codes["Name"][i]

print(list(set(regions)-set(countries_dict.keys())))
countries_dict['jp'] = "Japan"
countries_dict['id'] = "Indonesia"
countries_dict['ca'] = "Canada"

countries_dict

['jp', 'ca', 'id']

{'ar': 'Argentina',
 'au': 'Australia',
 'at': 'Austria',
 'be': 'Belgium',
 'bo': 'Bolivia',
 'br': 'Brazil',
 'bg': 'Bulgaria',
 'cl': 'Chile',
 'co': 'Colombia',
 'cy': 'Cyprus',
 'cz': 'Czech Republic',
 'dk': 'Denmark',
 'sv': 'El Salvador',
 'fi': 'Finland',
 'fr': 'France',
 'de': 'Germany',
 'hn': 'Honduras',
 'hk': 'Hong Kong',
 'hu': 'Hungary',
 'is': 'Iceland',
 'ie': 'Ireland',
 'it': 'Italy',
 'lv': 'Latvia',
 'lu': 'Luxembourg',
 'my': 'Malaysia',
 'mx': 'Mexico',
 'ni': 'Nicaragua',
 'no': 'Norway',
 'py': 'Paraguay',
 'pe': 'Peru',
 'ph': 'Philippines',
 'pl': 'Poland',
 'pt': 'Portugal',
 'sg': 'Singapore',
 'sk': 'Slovakia',
 'es': 'Spain',
 'se': 'Sweden',
 'ch': 'Switzerland',
 'tw': 'Taiwan',
 'tr': 'Turkey',
 'gb': 'United Kingdom',
 'uy': 'Uruguay',
 'us': 'USA',
 'jp': 'Japan',
 'id': 'Indonesia',
 'ca': 'Canada'}

In [16]:
year = "2017"
happiness = pd.read_csv("/Users/lalitha/Documents/worldhappinessmusic/happiness_data/"+year+".csv")
happiness["Danceability"] = np.nan
happiness["Valence"] = np.nan
happiness["Energy"] = np.nan
happiness

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual,Danceability,Valence,Energy
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027,NaN,NaN,NaN
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707,NaN,NaN,NaN
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715,NaN,NaN,NaN
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716,NaN,NaN,NaN
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,Rwanda,151,3.471,3.543030,3.398970,0.368746,0.945707,0.326425,0.581844,0.252756,0.455220,0.540061,NaN,NaN,NaN
151,Syria,152,3.462,3.663669,3.260331,0.777153,0.396103,0.500533,0.081539,0.493664,0.151347,1.061574,NaN,NaN,NaN
152,Tanzania,153,3.349,3.461430,3.236570,0.511136,1.041990,0.364509,0.390018,0.354256,0.066035,0.621130,NaN,NaN,NaN
153,Burundi,154,2.905,3.074690,2.735310,0.091623,0.629794,0.151611,0.059901,0.204435,0.084148,1.683024,NaN,NaN,NaN
154,Central African Republic,155,2.693,2.864884,2.521116,0.000000,0.000000,0.018773,0.270842,0.280876,0.056565,2.066005,NaN,NaN,NaN

In [14]:

for year in years:
    print(year)
    
    happiness = pd.read_csv("/Users/lalitha/Documents/worldhappinessmusic/happiness_data/"+year+".csv")
    happiness["Danceability"] = np.nan
    happiness["Valence"] = np.nan
    happiness["Energy"] = np.nan
    happiness
    break
    for region in regions:
        print(region)
        country_name = countries_dict[region]
        filepath = "/Users/lalitha/Documents/worldhappinessmusic/top50_"+year+"_audiofeatures/top50stats_"+region+"_"+year+".csv"
        df = pd.read_csv(filepath)
        
        avg_danceability=df["Danceability"].mean()
        avg_valence=df["Valence"].mean()
        avg_energy = df["Energy"].mean()
        
        happiness["Danceability"] = avg_danceability
        happiness["Valence"] = avg_valence
        happiness["Energy"] = avg_energy
        

    happiness.dropna()
    break

happiness

2017